### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by working-name** [airmessage/airmessage-server#10]
Not sure if this is the android app or the server but anywho, submitting it here.

When the android app loses connection which happens several hundred times per day while connected to my local wifi (that's because the fallback is the intranet address?), it sometimes decides to just send me the same notification over and over again. When I open the android up, I get 2 copies of the same messages - send and received. Then on the next notification I get 3 copies, and then 4. Haven't seen 5 yet, fingers crossed! 🤞

**Comment by tagavari** [comment]
This has been resolved in [version 4.1.1](https://github.com/airmessage/airmessage-server/releases/tag/v4.1.1). If you still encounter this bug on this version or later, please let me know!
