### ISSUE TITLE
When building, Zlib library not found and must be added manually

### ISSUE THREAD

**Issue by kylefmohr** [airmessage/airmessage-server#21]
When I tried to build server and (I believe) followed the requisite setup instructions, the build fails due to the fact that it can't locate the zlib dependency. I was able to workaround this by:

- going to File>Add Packages>Add Local and selecting the Zlib folder in the base of this repo
- I then went to the AirMessage target, General>Frameworks, Libraries, and Embedded Content, clicked '+'
- Locate Zlib library and click Add

I'm very new at Xcode/MacOS development, so I'm unsure how/if this is fixable from a project configuration standpoint, but I just wanted to document the steps in case anybody else ran into this as well.

**Comment by tagavari** [comment]
Thank you for bringing this up, this is good to know. Can I ask what version of macOS and Xcode you're using?

**Comment by kylefmohr** [comment]
Sure thing, I'm running macOS 12.4 and Xcode Version 13.4.1 (13F100)

**Comment by tagavari** [comment]
Did you clone the repo with `git clone`, or did you download the files as a zip from GitHub? I think that local Swift Package Manager packages don't work if they're not under version control

**Comment by kylefmohr** [comment]
Just double-checked, I did a git clone (--recursive, but don't think that matters) of airmessage-server

**Comment by tagavari** [comment]
That's interesting, I did a test on my computer where cloning the repository would have Zlib come up automatically as a build scheme, whereas downloading the zip file would cause it to only have AirMessageTests.

It's possible I've installed something on my computer that I don't know about. In any case, thanks again for reporting this!

**Comment by kylefmohr** [comment]
Let me run it back one more time and test again, it’s very possible it’s something minor I messed up. One sec.

**Comment by tagavari** [comment]
@kylefmohr Just want to follow up, were you able to test this? If not, no worries!

**Comment by kylefmohr** [comment]
Oh sorry to leave you hanging! I didn't have a chance to test it, I will close the issue, I'm sure it was something on my end. Thanks for following up, AirMessage has been incredibly helpful for me recently! So nice to be able to use iMessage/SMS from my Windows computers.
