### ISSUE TITLE
upgrading from v3 > v4 prevents messages ever loading

### ISSUE THREAD

**Issue by Geczy** [airmessage/airmessage-server#23]
v3 works great and can send texts etc, 3.4.1

but when downloading v4, fixing the privacy accessibility settings, running it, the client connects, the client can see the facetime experiemntal toggle being turned on, but it fails on `liteconversationretrieval / of length 0` so the client just never loads messages :( 

what coudl this issue be? i cleared cache on client and everything to confirm. is there cache in server i need to clear?

**Comment by tagavari** [comment]
Hmm, I'm not sure why no conversations would show up. There's no cache to clear, the server reads directly from the database.

Can I ask what version of macOS you're running?

**Comment by Geczy** [comment]
i'm on macos 12.4 ! i tried the clear permissions command too and it's still stuck on that error

**Comment by tagavari** [comment]
Resolved via Discord by upgrading to macOS 12.5
