### ISSUE TITLE
Is there a plan to add phone call feature?

### ISSUE THREAD

**Issue by deng-cy** [airmessage/airmessage-server#25]
Thank developers for this great software. I think it would be great to add a feature to make a phone call through Facetime.

**Comment by Hoodgail** [comment]
You can already accept facetime calls

**Comment by deng-cy** [comment]
Thanks for your reply. I meant calling a phone number (like cellular phone call).

**Comment by tagavari** [comment]
Unfortunately not, there's no easy way to implement this functionality. FaceTime is implemented through FaceTime links, but there's no such equivalent for phone call routing.

Unless you're referring to starting a regular phone call using your Android's phone built-in dialer

**Comment by deng-cy** [comment]
Thanks. What I want is to use the number on iPhone to call on my Android phone. I think it's more difficult to use built-in dialer to achieve this, unless I misunderstood.

**Comment by tagavari** [comment]
No, there are no plans to implement phone calls using an associated iPhone
