### ISSUE TITLE
Implement more aggressive lost connection detection

### ISSUE THREAD

**Issue by tagavari** [airmessage/airmessage-server#27]
When the server loses connection to AirMessage Connect, it may take a while for it to pick up on the fact that the connection has been severed and re-establish it. The server should check the health of the connection more frequently.

This can easily be recreated on laptops by running the server, then closing the lid for a few minutes. When the laptop is reopened, the server will still think it is connected, but no clients will be able to connect to it.

Reported by Avibee and others on Discord: https://discord.com/channels/992925221256450068/992929582439202908/1004535441212571769

This may be a duplicate of #13.

**Comment by aviavi123** [comment]
Here's a screenshot of server disconnection "no clients running" even though the preferences show I'm connected via my gmail account. The client log is blank, btw. However, sometimes opening AirMessage Android makes the server reconnect with the client.
<img width="356" alt="Screen Shot 2022-08-04 at 10 14 50 PM" src="https://user-images.githubusercontent.com/16562812/182990923-690ef623-058b-478b-9484-8c0aa7dfca0f.png">

**Comment by tagavari** [comment]
Duplicate of #13
