### ISSUE TITLE
Add AirMessage Server to Homebrew Cask

### ISSUE THREAD

**Issue by mariobrostech** [airmessage/airmessage-server#29]
Hi,

Is there any way that you could submit AirMessage Server to be included as a Homebrew Cask for users who'd prefer to use brew as their package manager?

Thanks in advance!

**Comment by tagavari** [comment]
Hi, thanks for the request!

While I can understand the convenience of managing apps through homebrew, I'm not sure if there's a large enough number of users who would use this to make it worthwhile.

AirMessage Server 4 supports installing updates remotely, so a cask would mostly only be useful for installation, which is a one-time action.

That being said, I'd like AirMessage to be able to accommodate a wide variety of use cases. If you or anyone else would like to maintain a homebrew cask for AirMessage, I would be happy to provide support.
