### ISSUE TITLE
Server crashes with "external error"; does not try to restart

### ISSUE THREAD

**Issue by JosephM101** [airmessage/airmessage-server#35]
I've had a repeating issue that occurs more frequently than I'd like. Often I will open the app, and it will say "Personal server not available". The server, in the menu bar, will say "An external error occurs." The server does not, from appearance, try to restart.

Might I suggest a retry-loop with a configurable threshold (maybe with a default of 5 retries before failing), and use/show a log window instead? I would strongly prefer this over having to connect to the Mac over VNC and click a button to restart the server: a process that should realistically be automated.

**Comment by tagavari** [comment]
Thanks for bringing this up! This is resolved in d9443a916d0a1c0bdda0e49a11a7119eb1bb92bc, which will be part of an update released today.

**Comment by JosephM101** [comment]
Thank you so much for acknowledging this so quickly!
